### ISSUE TITLE
Add columns

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-bench-backend#6]
Add the following columns:

- `cpuCoreCount`, type integer, indexed
- `cpuThreadCount`, type integer, indexed
- `renderThreadCount`, type integer, indexed
- `operatingSystem`, type string, indexed

Final order of columns:

1. `submissionDateTimeUtc`
2. `benchmarkVersion`
3. `benchmarkSceneId`
4. `cpuModel`
5. **`cpuCoreCount`**
6. **`cpuThreadCount`**
7. **`renderThreadCount`**
8. **`operatingSystem`**
9. `renderTime`

**Comment by flagollet** [comment]
Implement issue on #9

**Comment by dictoon** [comment]
Done.
